package mycode.main.Test;

import org.apache.commons.lang3.exception.ExceptionUtils;
import org.apache.http.HttpHost;
import org.apache.http.conn.HttpHostConnectException;

import java.lang.reflect.InvocationTargetException;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

/**
 * 此類別作為方便用(功能簡單單一)，不想一直開新的 
 */
public class SampleTest {
    
    private static Map<Integer, String> mappingMethods = new HashMap<Integer, String>();
    
    static {
        mappingMethods.put(1, "doJarFilter");/** {@link #doJarFilter()} **/
        mappingMethods.put(2, "doExceptionStart");/** {@link #doExceptionStart()} **/
    }

    public static void main(String[] args) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        SampleTest sampleTest = new SampleTest();
        sampleTest.getClass().getMethod(mappingMethods.get(2)).invoke(sampleTest);

    }
    
    public static void doExceptionStart() {
        try {
            doException();
        }catch (Exception e) {
            e.printStackTrace();
//            ExceptionUtils.getStackTrace(e);
            System.out.println("0: " + e.getCause().getMessage());
            System.out.println("1: " + e);
            System.out.println("2: " + e.getMessage());
            System.out.println("3: " + e.getStackTrace());
            System.out.println("4: " + e.getLocalizedMessage());
            System.out.println("5: " + e.getSuppressed());
            System.out.println("6: " + getRootCause(e).getMessage());
        }
    }

    public static void doJarFilter() {
        Set<String> filterData = new LinkedHashSet<>();
        for(String str : data) {
            filterData.add(str);
        }
        filterData.stream().forEach(System.out::println);
    }

    private static void doException() throws Exception {
        try {
            HttpHost host = new HttpHost("0.0.0.0", 8080, "http");
            throw new HttpHostConnectException(host, new java.net.ConnectException("Connection refused"));
        }catch (HttpHostConnectException e) {
            ExceptionUtils.getStackTrace(e);
            throw new Exception(e);
        }
    }

    private static Throwable getRootCause(Throwable throwable) {
        if (throwable.getCause() != null)
            return getRootCause(throwable.getCause());

        return throwable;
    }
    
    private static String[] data = new String[] {
            "aopalliance-1.0.jar",
            "c3p0-0.9.5.5.jar",
            "caffeine-2.9.3.jar",
            "checker-qual-3.19.0.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.16.0.jar",
            "commons-collections-3.2.2.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-text-1.4.jar",
            "error_prone_annotations-2.10.0.jar",
            "hamcrest-core-1.3.jar",
            "HikariCP-java7-2.4.13.jar",
            "httpclient-4.5.13.jar",
            "httpcore-4.4.13.jar",
            "ini4j-0.5.4.jar",
            "jackson-annotations-2.13.5.jar",
            "jackson-core-2.13.5.jar",
            "jackson-databind-2.13.5.jar",
            "javax.servlet-api-3.1.0.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jetty-http-9.4.55.v20240627.jar",
            "jetty-io-9.4.55.v20240627.jar",
            "jetty-security-9.4.55.v20240627.jar",
            "jetty-server-9.4.55.v20240627.jar",
            "jetty-servlet-9.4.55.v20240627.jar",
            "jetty-spring-9.4.55.v20240627.jar",
            "jetty-util-9.4.55.v20240627.jar",
            "jetty-util-ajax-9.4.55.v20240627.jar",
            "jetty-xml-9.4.55.v20240627.jar",
            "jul-to-slf4j-1.7.32.jar",
            "junit-4.13.2.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.20.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "caffeine-2.9.3.jar",
            "camel-bindy-2.20.4.jar",
            "camel-core-2.20.4.jar",
            "camel-http-common-2.20.4.jar",
            "camel-jetty9-2.20.4.jar",
            "camel-jetty-common-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "camel-sql-2.20.4.jar",
            "checker-qual-3.19.0.jar",
            "commons-codec-1.16.0.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-pool2-2.4.3.jar",
            "commons-text-1.4.jar",
            "error_prone_annotations-2.10.0.jar",
            "jackson-annotations-2.13.5.jar",
            "jackson-core-2.13.5.jar",
            "jackson-databind-2.13.5.jar",
            "javax.servlet-api-3.1.0.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jetty-client-9.4.55.v20240627.jar",
            "jetty-continuation-9.4.55.v20240627.jar",
            "jetty-http-9.4.55.v20240627.jar",
            "jetty-io-9.4.55.v20240627.jar",
            "jetty-jmx-9.4.55.v20240627.jar",
            "jetty-security-9.4.55.v20240627.jar",
            "jetty-server-9.4.55.v20240627.jar",
            "jetty-servlet-9.4.55.v20240627.jar",
            "jetty-servlets-9.4.55.v20240627.jar",
            "jetty-spring-9.4.55.v20240627.jar",
            "jetty-util-9.4.55.v20240627.jar",
            "jetty-util-ajax-9.4.55.v20240627.jar",
            "jetty-xml-9.4.55.v20240627.jar",
            "jul-to-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.19.jar",
            "mina-core-2.0.22.jar",
            "MinaPoolConnect-3.20.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "slf4j-api-1.7.32.jar",
            "SmsGWSpec-3.20.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "camel-bindy-2.20.4.jar",
            "camel-core-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "camel-sql-2.20.4.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.16.0.jar",
            "commons-collections-3.2.2.jar",
            "commons-configuration2-2.11.0.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-text-1.12.0.jar",
            "HikariCP-java7-2.4.13.jar",
            "httpclient-4.5.13.jar",
            "httpcore-4.4.13.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.19.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "camel-bindy-2.20.4.jar",
            "camel-core-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "camel-sql-2.20.4.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.16.0.jar",
            "commons-collections-3.2.2.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-text-1.4.jar",
            "HikariCP-java7-2.4.13.jar",
            "httpclient-4.5.13.jar",
            "httpcore-4.4.13.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.19.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "camel-core-2.20.4.jar",
            "camel-netty4-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "netty-buffer-4.1.97.Final.jar",
            "netty-codec-4.1.97.Final.jar",
            "netty-common-4.1.97.Final.jar",
            "netty-handler-4.1.97.Final.jar",
            "netty-resolver-4.1.97.Final.jar",
            "netty-transport-4.1.97.Final.jar",
            "netty-transport-native-unix-common-4.1.97.Final.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "camel-bindy-2.20.4.jar",
            "camel-core-2.20.4.jar",
            "camel-mail-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "camel-sql-2.20.4.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.16.0.jar",
            "commons-collections-3.2.2.jar",
            "commons-configuration2-2.11.0.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-text-1.12.0.jar",
            "hamcrest-core-1.3.jar",
            "HikariCP-java7-2.4.13.jar",
            "httpclient-4.5.13.jar",
            "httpcore-4.4.13.jar",
            "javax.mail-1.6.0.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "junit-4.13.2.jar",
            "log4j-over-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.20.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-context-support-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "camel-core-2.20.4.jar",
            "camel-mail-2.20.4.jar",
            "camel-quartz2-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.16.0.jar",
            "commons-collections-3.2.2.jar",
            "commons-configuration2-2.11.0.jar",
            "commons-io-2.11.0.jar",
            "commons-lang3-3.14.0.jar",
            "commons-logging-1.3.2.jar",
            "commons-text-1.12.0.jar",
            "HikariCP-java7-2.4.13.jar",
            "javax.mail-1.6.0.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "log4j-over-slf4j-1.7.32.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.20.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "c3p0-0.9.5.5.jar",
            "camel-core-2.20.4.jar",
            "camel-mail-2.20.4.jar",
            "camel-quartz2-2.20.4.jar",
            "camel-spring-2.20.4.jar",
            "commons-beanutils-1.9.4.jar",
            "commons-codec-1.17.1.jar",
            "commons-collections4-4.4.jar",
            "commons-collections-3.2.2.jar",
            "commons-compress-1.27.0.jar",
            "commons-configuration2-2.11.0.jar",
            "commons-io-2.16.1.jar",
            "commons-lang3-3.14.0.jar",
            "commons-logging-1.3.2.jar",
            "commons-math3-3.6.1.jar",
            "commons-text-1.12.0.jar",
            "curvesapi-1.07.jar",
            "HikariCP-4.0.3.jar",
            "HikariCP-java7-2.4.13.jar",
            "javax.mail-1.6.0.jar",
            "jaxb-core-2.2.11.jar",
            "jaxb-impl-2.2.11.jar",
            "jcl-over-slf4j-1.7.32.jar",
            "jul-to-slf4j-1.7.32.jar",
            "log4j-api-2.22.0.jar",
            "log4j-core-2.22.0.jar",
            "logback-access-1.2.13.jar",
            "logback-classic-1.2.13.jar",
            "logback-core-1.2.13.jar",
            "mchange-commons-java-0.2.19.jar",
            "mssql-jdbc-6.2.2.jre8.jar",
            "poi-5.2.2.jar",
            "poi-ooxml-5.2.2.jar",
            "poi-ooxml-lite-5.2.2.jar",
            "quartz-2.3.2.jar",
            "slf4j-api-1.7.32.jar",
            "SparseBitSet-1.2.jar",
            "spring-aop-5.3.39.jar",
            "spring-beans-5.3.39.jar",
            "spring-context-5.3.39.jar",
            "spring-core-5.3.39.jar",
            "spring-expression-5.3.39.jar",
            "spring-jcl-5.3.39.jar",
            "spring-jdbc-5.3.39.jar",
            "spring-tx-5.3.39.jar",
            "xmlbeans-5.0.3.jar"
    };
}
